insert into FMD180EXCEL1(hyno,ccbh)
SELECT  TT.HYNO,'{$@_cwbh_@$}H' FROM 
(SELECT C.HYNO,CASE WHEN ISNULL(D.TEL,'') = '' THEN C.TEL ELSE D.TEL END AS TEL FROM 
(SELECT DIS.* FROM 
(SELECT  V1.HYNO AS HYNO,V1.TEL AS TEL FROM 
(select HYNO,TEL from zkbak) V1 ) DIS ) C
LEFT JOIN(SELECT HYNO,TEL,HYM FROM FHD030) D ON C.HYNO = D.HYNO ) TT
WHERE REPLACE(TT.TEL,'-','') IN (SELECT REPLACE(AA.TEL, '-', '')
FROM (SELECT CASE WHEN ISNULL(B.TEL, '') = '' THEN A.TEL ELSE B.TEL END AS TEL
FROM (SELECT DISTINCT  HYNO, TEL FROM 
(select HYNO,TEL from zkbak) TM ) A
LEFT JOIN (SELECT HYNO,TEL FROM FHD030) B ON A.HYNO = B.HYNO ) AA
WHERE ISNULL(AA.TEL, '') <> ''
GROUP BY REPLACE(AA.TEL, '-', '')
HAVING COUNT(AA.TEL) > 1)  