SELECT distinct 
   CONVERT(INT,CONVERT(NVARCHAR,ROW_NUMBER()  OVER(PARTITION BY A.SALONNO ORDER BY A.SALONNO))) AS SEQ, 
     A.SALONNO,A.HYNO,A.HYZB,A.HYM,A.HYMKN ,A.CHGRSLNO,ISNULL(C2.SLNMC,'')CHSLNMC,ISNULL(B.MC,'') ZS,
    A.SNYR,ISNULL(D.ZJGRJE,'') ZJGRJE,ISNULL(D.ZJGRR,'') ZJGRR,isnull(c.SLNDELDT,''),A.TEL,
    a.QHYNO,A.QHYM,ISNULL(E.DLDLLQF,'') DLDLLQF ,
    ISNULL(E.ZTQF,'') ZTQF ,ISNULL(E.PHASE,'') PHASE,E.CCBH,E.QHCALLRS,
 A.BLOCKNO,F.MC
FROM  CALL010 A 
LEFT JOIN FMD010 A0 ON A.HYNO =A0.HYNO 
LEFT JOIN FMD080 B ON  A.DDFXBH=B.ID
LEFT JOIN FMD070 C ON A.SALONNO=C.SLNCD
LEFT JOIN FMD070 C2 ON A.CHGRSLNO =C2.SLNCD
LEFT JOIN FMD060 D ON A.HYNO=D.HYNO 
LEFT JOIN FHD030 E ON A.HYNO=E.HYNO 
LEFT JOIN FMD110 F ON A.BLOCKNO = F.MCKEY AND F.GLBH = '004' 
WHERE